apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "pion.fullname" . }}-proxy
  labels:
    app: {{ template "pion.name" . }}
    component: proxy
    network-zone: orange
    chart: {{ template "pion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/limit-connections: "100"
spec:
  tls:
  - hosts:
    {{- range .Values.proxy.ingress.hosts }}
      - {{ . }}
    {{- end }}
  rules:
  {{- range .Values.proxy.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "pion.fullname" $ }}-proxy
            servicePort: 8080
  {{- end }}
