apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pion.fullname" . }}-ui
  labels:
    app: {{ template "pion.name" . }}
    component: ui
    chart: {{ template "pion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pion.name" . }}
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pion.name" . }}
        component: ui
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000    
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          args:
          - /opt/pion-ui
          - --stderrthreshold=INFO
          - --v=2
          - --ldap-host={{ .Values.ldap.host }}
          - --ldap-type={{ .Values.ldap.type }}
          - --ldap-binddn=$(LDAP_USER)
          - --ldap-bindpassword=$(LDAP_PASSWORD)
          - --ldap-userbase={{ .Values.ldap.userdn }}
          - --ldap-groupbase={{ .Values.ldap.groupdn }}
          - --ldap-userclass={{ .Values.ldap.userclass }}
          - --ldap-groupclass={{ .Values.ldap.groupclass }}
          - --token-ttl={{ .Values.ui.tokenTTL }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          env:
          - name: STS_SERVICE_URL
            value: http://{{ template "pion.fullname" . }}-sts:8080
          - name: MANAGER_SERVICE_URL
            value: http://{{ template "pion.fullname" . }}-manager:8080
          - name: MINIO_SERVICE_URL
            value: {{ template "pion.minio-service-url" . }}
          - name: LDAP_USER
            valueFrom:
              secretKeyRef:
                key: ldap-user
                name: {{ template "pion.fullname" . }}-ui
          - name: LDAP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ldap-password
                name: {{ template "pion.fullname" . }}-ui
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: {{ .Values.minioRelease }}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secretkey
                name: {{ .Values.minioRelease }}
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
