apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "pion.name" . }}
    component: ui
    chart: {{ template "pion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "pion.fullname" . }}-ui
data:
  ldap-user: {{ .Values.ldap.username | b64enc | quote }}
  ldap-password: {{ .Values.ldap.password | b64enc | quote }}
